class forgotPasswordPage{
      visit()
    {
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/requestPasswordResetCode')
    }
    intercept()
    {
        cy.intercept('GET','https://opensource-demo.orangehrmlive.com/web/index.php/core/i18n/messages').as('loginpage')
    }
    interceptWait()
    {
            cy.wait('@loginpage').then((intercept)=>{
            expect(intercept.response.statusCode).to.equal(200)
        })
    }
    requiredError()
    {
        cy.get('.oxd-input-field-error-message').should('be.visible')
    }
    resetButton()
    {
        cy.get('.oxd-button--secondary').click()
    }
    cancelButton()
    {
        cy.get('.oxd-button--ghost').click()
    }
    forgotPageCheck()
    {
        cy.url().should('include','requestPasswordResetCode')
    }
    inputField(input)
    {
        cy.get('[name="username"]').type(input)
    }
    sendPasswordReset()
    {
        cy.get('.orangehrm-card-container').should('be.visible')
    }
    sendPasswordResetCheck()
    {
        cy.url().should('include','sendPasswordReset')
    }
}
export default new forgotPasswordPage()